/**
 * Generates supabase/seed.sql from the static data in data/*.ts so the
 * Supabase project starts out with the same content as the bundled demo.
 *
 * Usage: node scripts/generate-seed.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';

const COLLECTIONS = [
  { file: 'data/events.ts', table: 'events' },
  { file: 'data/activities.ts', table: 'activities' },
  { file: 'data/seva.ts', table: 'seva_categories' },
  { file: 'data/gallery.ts', table: 'gallery_images' },
  { file: 'data/impact.ts', table: 'impact_stats' },
];

/** Evaluate a data/*.ts module (plain object literals + type annotations). */
function loadCollection(file) {
  let src = readFileSync(file, 'utf8');
  src = src.replace(/^import .*$/m, '');
  src = src.replace(/export const \w+\s*:\s*[\w<>[\], |]+\s*=/, 'module.exports =');
  const mod = { exports: {} };
  new Function('module', src)(mod);
  return mod.exports;
}

function sqlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function toSql(value) {
  if (value === undefined || value === null) return 'null';
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value) || typeof value === 'object') {
    return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  }
  return sqlString(value);
}

const statements = [];
statements.push('-- Auto-generated by scripts/generate-seed.mjs — do not edit by hand.');
statements.push('-- Run after schema.sql to load the demo content.');

for (const { file, table } of COLLECTIONS) {
  const rows = loadCollection(file);
  if (!Array.isArray(rows) || rows.length === 0) continue;
  const columns = Object.keys(rows[0]);
  statements.push(`\n-- ${table}`);
  for (const row of rows) {
    const cols = columns.map((c) => (/^[a-z_][a-z0-9_]*$/.test(c) ? c : `"${c}"`));
    const values = columns.map((c) => toSql(row[c])).join(', ');
    statements.push(
      `insert into public.${table} (${cols.join(', ')}) values (${values}) on conflict (id) do nothing;`
    );
  }
}

writeFileSync('supabase/seed.sql', statements.join('\n') + '\n');
console.log(`Wrote supabase/seed.sql (${statements.length - 2} rows).`);
